### ISSUE TITLE
Pasted images results in empty line

### ISSUE THREAD

**Issue by ziggiman** [thorsager/t-slacker#17]
When an image is pasted (without any additional test) an empty line occurs - and nothing else. An ideal solution might be to show the URL to the image found on the slack server. Like: https://files.slack.com/files-pri/XXXX-XXXX/image.png

**Comment by thorsager** [comment]
@ziggiman I have tried to add some code the will iterate all attached files and present a link, if possible please take a look.

**Comment by ziggiman** [comment]
Looks much better! Solution seems to work :-)
